# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pyProj\new-uwin\modern_modify_password\modify_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from modern_gui.qt_core import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(611, 366)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("QWidget {background-color: rgb(44,49,60);\n"
"border-radius: 8px;\n"
"border: 2px solid #343b48;}")
        self.lineEditNewPassword = QLineEdit(Form)
        self.lineEditNewPassword.setGeometry(QRect(195, 100, 355, 40))
        self.lineEditNewPassword.setMinimumSize(QSize(0, 40))
        self.lineEditNewPassword.setStyleSheet("QLineEdit {\n"
"      color: rgb(220,225,236);\n"
"      font: 15pt \"Verdana\";\n"
"      border: None;\n"
"      border-bottom-color: white;\n"
"      border-radius: 8px;\n"
"      padding: 0 8px;\n"
"      background: rgb(52,59,72);\n"
"      selection-background-color: darkgray;\n"
"}")
        self.lineEditNewPassword.setEchoMode(QLineEdit.Password)
        self.lineEditNewPassword.setObjectName("lineEditNewPassword")
        self.pushButtonModifyPassword = QPushButton(Form)
        self.pushButtonModifyPassword.setGeometry(QRect(50, 226, 500, 48))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonModifyPassword.sizePolicy().hasHeightForWidth())
        self.pushButtonModifyPassword.setSizePolicy(sizePolicy)
        self.pushButtonModifyPassword.setMinimumSize(QSize(0, 45))
        font = QFont()
        font.setFamily("Verdana")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(QFont.Weight(50))
        font.setKerning(True)
        self.pushButtonModifyPassword.setFont(font)
        self.pushButtonModifyPassword.setAutoFillBackground(False)
        self.pushButtonModifyPassword.setStyleSheet("color: rgb(231, 231, 231);\n"
"font: 17pt \"Verdana\";\n"
"border: 2px solid rgb(79,159,238);\n"
"padding: 5px;\n"
"border-radius: 8px;\n"
"opacity: 200;\n"
"")
        self.pushButtonModifyPassword.setAutoDefault(False)
        self.pushButtonModifyPassword.setDefault(False)
        self.pushButtonModifyPassword.setFlat(False)
        self.pushButtonModifyPassword.setObjectName("pushButtonModifyPassword")
        self.pushButtonCancel = QPushButton(Form)
        self.pushButtonCancel.setGeometry(QRect(50, 280, 500, 48))
        self.pushButtonCancel.setMinimumSize(QSize(0, 45))
        self.pushButtonCancel.setStyleSheet("color: rgb(231, 231, 231);\n"
"font: 17pt \"Verdana\";\n"
"border: 2px solid rgb(79,159,238);\n"
"padding: 5px;\n"
"border-radius: 8px;\n"
"opacity: 200;\n"
"")
        self.pushButtonCancel.setDefault(False)
        self.pushButtonCancel.setFlat(False)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.pushButtonClose = QPushButton(Form)
        self.pushButtonClose.setGeometry(QRect(577, 8, 35, 25))
        self.pushButtonClose.setMinimumSize(QSize(35, 25))
        self.pushButtonClose.setMaximumSize(QSize(35, 25))
        self.pushButtonClose.setStyleSheet("color: white;\n"
"font: 12pt \"Arial\";")
        self.pushButtonClose.setFlat(True)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.lineEditOldPassword = QLineEdit(Form)
        self.lineEditOldPassword.setGeometry(QRect(195, 40, 355, 40))
        self.lineEditOldPassword.setMinimumSize(QSize(0, 40))
        self.lineEditOldPassword.setStyleSheet("QLineEdit {\n"
"      color: rgb(220,225,236);\n"
"      font: 15pt \"Verdana\";\n"
"      border: None;\n"
"      border-bottom-color: white;\n"
"      border-radius: 8px;\n"
"      padding: 0 8px;\n"
"      background: rgb(52,59,72);\n"
"      selection-background-color: darkgray;\n"
"}")
        self.lineEditOldPassword.setEchoMode(QLineEdit.Password)
        self.lineEditOldPassword.setObjectName("lineEditOldPassword")
        self.label_5 = QLabel(Form)
        self.label_5.setGeometry(QRect(28, 40, 161, 44))
        self.label_5.setStyleSheet("color: rgb(231, 231, 231);\n"
"font: 17pt \"Verdana\";\n"
"padding: 5px;\n"
"border-radius: 8px;\n"
"opacity: 200;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QLabel(Form)
        self.label_6.setGeometry(QRect(30, 100, 161, 44))
        self.label_6.setStyleSheet("color: rgb(231, 231, 231);\n"
"font: 17pt \"Verdana\";\n"
"padding: 5px;\n"
"border-radius: 8px;\n"
"opacity: 200;")
        self.label_6.setObjectName("label_6")
        self.lineEditConfirmPassword = QLineEdit(Form)
        self.lineEditConfirmPassword.setGeometry(QRect(195, 160, 355, 40))
        self.lineEditConfirmPassword.setMinimumSize(QSize(0, 40))
        self.lineEditConfirmPassword.setStyleSheet("QLineEdit {\n"
"      color: rgb(220,225,236);\n"
"      font: 15pt \"Verdana\";\n"
"      border: None;\n"
"      border-bottom-color: white;\n"
"      border-radius: 8px;\n"
"      padding: 0 8px;\n"
"      background: rgb(52,59,72);\n"
"      selection-background-color: darkgray;\n"
"}")
        self.lineEditConfirmPassword.setEchoMode(QLineEdit.Password)
        self.lineEditConfirmPassword.setObjectName("lineEditConfirmPassword")
        self.label_7 = QLabel(Form)
        self.label_7.setGeometry(QRect(30, 160, 161, 44))
        self.label_7.setStyleSheet("color: rgb(231, 231, 231);\n"
"font: 17pt \"Verdana\";\n"
"padding: 5px;\n"
"border-radius: 8px;\n"
"opacity: 200;")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEditOldPassword, self.lineEditNewPassword)
        Form.setTabOrder(self.lineEditNewPassword, self.lineEditConfirmPassword)
        Form.setTabOrder(self.lineEditConfirmPassword, self.pushButtonModifyPassword)
        Form.setTabOrder(self.pushButtonModifyPassword, self.pushButtonCancel)
        Form.setTabOrder(self.pushButtonCancel, self.pushButtonClose)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "注册"))
        self.pushButtonModifyPassword.setText(_translate("Form", "提交"))
        self.pushButtonCancel.setText(_translate("Form", "取消"))
        self.pushButtonClose.setText(_translate("Form", "X"))
        self.label_5.setText(_translate("Form", "输入旧密码"))
        self.label_6.setText(_translate("Form", "输入新密码"))
        self.label_7.setText(_translate("Form", "确认新密码"))
