# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Uproject\new-uwin\modern_gui\gui\uis\pages\register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from modern_gui.qt_core import *


class Ui_RegisterWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 444)
        self.horizontalLayoutWidget = QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QRect(-1, 160, 741, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("注册", "Form"))
