# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pyProj\new-uwin\ui\ui_error_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from modern_gui.qt_core import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(389, 88)
        self.pushButton = QPushButton(Form)
        self.pushButton.setGeometry(QRect(160, 50, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QLabel(Form)
        self.label.setGeometry(QRect(70, 10, 251, 20))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "确认"))
